# Generated by Django 3.1.4 on 2020-12-26 00:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)])),
                ('dob', models.DateField()),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('picture', models.ImageField(blank=True, default='defpfp.jpg', null=True, upload_to='')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('forum_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='forum.forumuser')),
            ],
        ),
        migrations.CreateModel(
            name='ForumPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=3000, validators=[django.core.validators.MinLengthValidator(20)])),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('comments', models.IntegerField(blank=True, default=0, null=True)),
                ('upvotes', models.IntegerField(blank=True, default=0, null=True)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.profile')),
            ],
        ),
    ]
