# Generated by Django 3.1.4 on 2020-12-27 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_auto_20201226_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, default='defpfp.jpg', null=True, upload_to='profiles/'),
        ),
    ]
