# Generated by Django 3.1.4 on 2020-12-28 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_auto_20201227_0005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forumpost',
            old_name='comments',
            new_name='replies',
        ),
    ]
