# Generated by Django 3.1.4 on 2020-12-28 06:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='date_replied',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
