# Generated by Django 3.1.4 on 2020-12-28 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_reply_date_replied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumpost',
            name='replies',
        ),
    ]
